name: cherry-top
version: '0.0.0'

category: Hardware
description: Cherry Top controls [BlinkStick](https://www.blinkstick.com)s.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/cherry-top
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
synopsis: Control BlinkSticks

dependencies:
  base: '>= 4.11.1 && < 4.12'
  bytestring: '>= 0.10.8 && < 0.11'
  text: '>= 1.2.3 && < 1.3'
  usb: '>= 1.3.0 && < 1.4'
  vector: '>= 0.12.0 && < 0.13'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

executable:
  dependencies: cherry-top
  ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
  main: Main.hs
  source-dirs: executables

tests:
  cherry-top-doctest:
    dependencies:
      doctest: '>= 0.16.0 && < 0.17'
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: tests
  cherry-top-readme:
    dependencies:
      cherry-top: null
      markdown-unlit: '>= 0.5.0 && < 0.6'
    ghc-options: -pgmL markdown-unlit
    main: README.lhs
