category: Hardware
description: Cherry Top controls BlinkSticks.
executables:
  blinkstick:
    dependencies: cherry-top
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.markdown
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
github: tfausak/cherry-top
library:
  dependencies:
  - base ==4.9.*
  - bytestring ==0.10.*
  - text ==1.2.*
  - usb ==1.3.*
  - vector ==0.11.*
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: cherry-top
synopsis: ! "\U0001F6A8 Control BlinkSticks"
version: '0.0.0'
