category: Hardware
description: Cherry Top controls <https://www.blinkstick.com BlinkStick>s.
executables:
  cherry-top:
    dependencies: cherry-top
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.markdown
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
github: tfausak/cherry-top
library:
  dependencies:
  - base ==4.9.*
  - bytestring ==0.10.*
  - text ==1.2.*
  - usb ==1.3.*
  - vector ==0.11.*
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: cherry-top
synopsis: Control BlinkSticks
tests:
  cherry-top-doctest:
    dependencies:
    - base
    - doctest ==0.11.*
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: DocTest.hs
    source-dirs: test-suite
  cherry-top-readme:
    dependencies:
    - base
    - cherry-top
    - markdown-unlit ==0.4.*
    - text
    - usb
    ghc-options: -pgmL markdown-unlit
    main: README.lhs
version: '0.0.0'
